### ISSUE TITLE
mssql::protocol::pre_login::Encrypt is private

### ISSUE THREAD

**Issue by mrpgraae** [lovasoa/sqlx-oldapi#9]
I know you literally implemented this 4 days ago, but I'm trying to connect to an Azure SQL Database with `MssqlConnectOptions` and the `encrypt` method takes an instance of `mssql::protocol::pre_login::Encrypt` which is private. I think this has to be a bug, right?

**Comment by lovasoa** [comment]
Thanks for letting me know, and sorry for the delay !

**Comment by mrpgraae** [comment]
> Thanks for letting me know, and sorry for the delay !

No problem. I just used a connection string with the encrypt options as a workaround.
